name: Build and Test

on:
  push:
    branches:
      - develop
      - release
  pull_request:
    branches:
      - develop
      - release

jobs:
  docker:
    name: Docker compose Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose up -d --build

      - name: Test WebService and Traefik
        run: sleep 3 && curl -sSf http://localhost:80/v1/contacts && curl -sSf http://localhost:8080/dashboard/#/

      - name: Stop containers
        if: always()
        run: docker-compose down