name: Build Docker Compose

on:
  push:
    branches:
      - develop
      - release
  pull_request:
    branches:
      - develop
      - release

jobs:
  dockercompose:
    name: Docker Compose Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start containers
        run: docker-compose up -d --build
      - name: Test Gatway web service
        run: |
          sleep 3
          curl --fail http://localhost/v1/contacts
      - name: Stop containers
        if: always()
        run: docker-compose down
