name: Build Docker Image

on:
  push:
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - develop

jobs:
  docker:
    name: Docker Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./WebService/Dockerfile
          push: true
          tags: apodini/examplewebservice:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
